import { useCallback, useEffect, useState } from "react";
import { apiFetch, fmtDate } from "../lib/api";
import { Empty, LoadError, Modal, Page, Spinner, useToast } from "../components/ui";

interface Task { id: string; type: string; title: string; body: string | null; dueAt: string; status: string; campaignId: string | null; contactId?: string | null; lead: { id: string; fullName: string | null; title: string | null; email: string | null; linkedinUrl: string | null; phone: string | null; whatsapp: string | null; company: { name: string | null; domain: string } | null } | null }

const ICON: Record<string, string> = { linkedin_connect: "in+", linkedin_message: "in✉", call: "☎", whatsapp: "wa", task: "☐" };

export function TasksPage() {
  const [rows, setRows] = useState<Task[]>([]);
  const [status, setStatus] = useState("pending");
  const [loading, setLoading] = useState(true);
  const { toast, Toast } = useToast();
  const [listErr, setListErr] = useState<string | null>(null);
  const [addOpen, setAddOpen] = useState(false);
  const load = useCallback(() => {
    // .finally without .catch turned a server error into "No tasks", which reads as an
    // empty queue rather than as a page that failed to load.
    apiFetch<{ tasks: Task[] }>("GET", `/v1/tools/tasks?status=${status}`)
      .then((r) => { setRows(r.tasks); setListErr(null); })
      .catch((e) => setListErr((e as Error).message))
      .finally(() => setLoading(false));
  }, [status]);
  useEffect(() => { load(); const t = setInterval(load, 10000); return () => clearInterval(t); }, [load]);
  const done = async (t: Task, outcome: "done" | "skipped") => {
    try { await apiFetch("POST", `/v1/tools/tasks/${t.id}/complete`, { outcome }); // Only a task generated by a campaign step (it carries the enrolment's contactId, which
    // is what the server advances) has a sequence to continue; a one-off task just closes.
    const inSequence = !!t.contactId;
    toast(outcome === "done" ? (inSequence ? "Done - sequence continues" : "Task done") : inSequence ? "Skipped - sequence continues" : "Task skipped"); load(); } catch (e) { toast((e as Error).message, "err"); }
  };
  return (
    <Page title="Tasks" subtitle="Human steps from your multichannel sequences: LinkedIn connects and messages, calls, WhatsApp. Complete a task and the sequence moves to the next step." actions={<><select className="input w-36" value={status} onChange={(e) => setStatus(e.target.value)}><option value="pending">Pending</option><option value="done">Done</option><option value="skipped">Skipped</option><option value="all">All</option></select><button className="btn-primary" onClick={() => setAddOpen(true)}>Add task</button></>}>
      {Toast}
      {loading ? <Spinner /> : listErr && rows.length === 0 ? <LoadError message={listErr} onRetry={load} /> : rows.length === 0 ? <Empty title="No tasks" hint="Tasks appear here as contacts reach a LinkedIn, call or WhatsApp step in a campaign - and you can add a one-off reminder yourself." action={<button className="btn-primary" onClick={() => setAddOpen(true)}>Add task</button>} /> : (
        <div className="space-y-3">
          {rows.map((t) => (
            <div key={t.id} className="card p-4">
              <div className="flex flex-wrap items-start gap-3">
                <span className="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-brand-50 text-xs font-bold text-brand-600">{ICON[t.type] ?? "☐"}</span>
                <div className="min-w-0 flex-1">
                  <div className="font-medium">{t.title}</div>
                  {t.lead && <div className="text-xs text-ink-400">{[t.lead.title, t.lead.company?.name ?? t.lead.company?.domain].filter(Boolean).join(" · ")} {t.lead.linkedinUrl && <a className="ml-2 text-brand-600" href={t.lead.linkedinUrl} target="_blank" rel="noreferrer">Open LinkedIn ↗</a>}{t.lead.phone && <span className="ml-2">{t.lead.phone}</span>}{t.type === "whatsapp" && (t.lead.whatsapp ?? t.lead.phone) && <a className="ml-2 text-emerald-600" href={`https://wa.me/${(t.lead.whatsapp ?? t.lead.phone ?? "").replace(/\D/g, "")}?text=${encodeURIComponent(t.body ?? "")}`} target="_blank" rel="noreferrer">Open WhatsApp ↗</a>}</div>}
                  {t.body && <pre className="mt-2 whitespace-pre-wrap rounded-lg bg-cream p-3 font-sans text-sm text-ink-200">{t.body}</pre>}
                  <div className="mt-1 text-xs text-ink-500">Due {fmtDate(t.dueAt)}</div>
                </div>
                {t.status === "pending" && <div className="flex gap-2"><button className="btn-secondary" disabled={!t.body} title={t.body ? undefined : "Nothing to copy"} onClick={() => t.body && navigator.clipboard.writeText(t.body).then(() => toast("Copied"), () => toast("Couldn't copy - select the text instead", "err"))}>Copy</button><button className="btn-secondary" onClick={() => done(t, "skipped")}>Skip</button><button className="btn-primary" onClick={() => done(t, "done")}>Mark done</button></div>}
              </div>
            </div>
          ))}
        </div>
      )}
      <AddTaskModal open={addOpen} onClose={() => setAddOpen(false)} onDone={() => { setAddOpen(false); setStatus("pending"); load(); }} toast={toast} />
    </Page>
  );
}

/**
 * A one-off follow-up.
 *
 * The endpoint for this has always existed; the page was read-and-complete only, so the
 * empty state told people tasks only ever arrive from a campaign step. "Call her back on
 * Thursday" had nowhere to live, which is the first thing anyone wants from a task list.
 */
function AddTaskModal({ open, onClose, onDone, toast }: { open: boolean; onClose: () => void; onDone: () => void; toast: (m: string, k?: "ok" | "err") => void }) {
  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [type, setType] = useState("task");
  const [dueAt, setDueAt] = useState("");
  const [busy, setBusy] = useState(false);

  useEffect(() => { if (open) { setTitle(""); setBody(""); setType("task"); setDueAt(""); } }, [open]);

  const save = async () => {
    if (!title.trim() || busy) return;
    setBusy(true);
    try {
      await apiFetch("POST", "/v1/tools/tasks", {
        title: title.trim(),
        type,
        body: body.trim() || undefined,
        // datetime-local has no timezone, so it is read as local time and sent as an
        // instant - which is what the server's .datetime() validator expects.
        dueAt: dueAt ? new Date(dueAt).toISOString() : undefined,
      });
      toast("Task added");
      onDone();
    } catch (e) { toast((e as Error).message, "err"); } finally { setBusy(false); }
  };

  return (
    <Modal open={open} onClose={onClose} title="Add a task">
      <div className="space-y-3">
        <div>
          <label className="label" htmlFor="task-title">What needs doing</label>
          <input id="task-title" className="input" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Call Priya back about the pilot" />
        </div>
        <div className="grid gap-3 sm:grid-cols-2">
          <div>
            <label className="label" htmlFor="task-type">Type</label>
            <select id="task-type" className="input" value={type} onChange={(e) => setType(e.target.value)}>
              <option value="task">Task</option>
              <option value="call">Call</option>
              <option value="linkedin_message">LinkedIn message</option>
              <option value="linkedin_connect">LinkedIn connect</option>
              <option value="whatsapp">WhatsApp</option>
            </select>
          </div>
          <div>
            <label className="label" htmlFor="task-due">Due</label>
            <input id="task-due" className="input" type="datetime-local" value={dueAt} onChange={(e) => setDueAt(e.target.value)} />
            <div className="mt-1 text-xs text-ink-400">Leave blank for now.</div>
          </div>
        </div>
        <div>
          <label className="label" htmlFor="task-body">Notes (optional)</label>
          <textarea id="task-body" className="input h-24" value={body} onChange={(e) => setBody(e.target.value)} placeholder="Anything you want in front of you when you pick this up." />
        </div>
        <div className="flex justify-end gap-2">
          <button className="btn-secondary" onClick={onClose}>Cancel</button>
          <button className="btn-primary" disabled={busy || !title.trim()} onClick={save}>{busy ? "…" : "Add task"}</button>
        </div>
      </div>
    </Modal>
  );
}
